"""Manual scenarios for the validated vehicle model."""

from vehicle import Car


car = Car("Volvo", "V60")

print("=== Startläge ===")
print("Motor igång:", car.is_running)
print("Hastighet:", car.speed)
print("Bränsle:", car.fuel, "/", car.max_fuel)
print()

print("=== Test 1: Stoppa en redan stoppad bil ===")
print("Anrop: car.stop()")
result = car.stop()
print("Returnerar:", result)
print("Motor igång efteråt:", car.is_running)
print()
print("Borde en operation som inte faktiskt ändrar något räknas som lyckad?")
print()

print("=== Test 2: Accelerera när bilen är stoppad ===")
print("Anrop: car.accelerate(50)")
result = car.accelerate(50)
print("Returnerar:", result)
print("Motor igång:", car.is_running)
print("Hastighet efteråt:", car.speed)
print()
print("Borde bilen kunna accelerera när den är stoppad?")
print()

print("=== Test 3: Bromsa mer än aktuell hastighet ===")
print("Hastighet före:", car.speed)
print("Anrop: car.brake(100)")
result = car.brake(100)
print("Returnerar:", result)
print("Hastighet efteråt:", car.speed)
print()
print("Borde hastigheten kunna bli negativ?")
print()

print("=== Test 4: Tanka med negativ mängd ===")
print("Bränsle före:", car.fuel)
print("Anrop: car.refuel(-10)")
result = car.refuel(-10)
print("Returnerar:", result)
print("Bränsle efteråt:", car.fuel)
print()
print("Borde en tankning kunna minska mängden bränsle?")
print()

print("=== Läge efter test 1-4 ===")
print("Motor igång:", car.is_running)
print("Hastighet:", car.speed)
print("Bränsle:", car.fuel, "/", car.max_fuel)

print()
print("=== Test 5: Starta två gånger ===")
print("Anrop: car.start()")
result = car.start()
print("Returnerar:", result)
print("Anrop: car.start()")
result = car.start()
print("Returnerar:", result)
print("Motor igång efteråt:", car.is_running)
print()

print("=== Test 6: Accelerera med ogiltig och giltig mängd ===")
print("Anrop: car.accelerate(-5)")
result = car.accelerate(-5)
print("Returnerar:", result)
print("Anrop: car.accelerate(20)")
result = car.accelerate(20)
print("Returnerar:", result)
print("Hastighet efteråt:", car.speed)
print()

print("=== Test 7: Tanka mer än tanken rymmer och en giltig mängd ===")
print("Anrop: car.refuel(30)")
result = car.refuel(30)
print("Returnerar:", result)
print("Anrop: car.refuel(10)")
result = car.refuel(10)
print("Returnerar:", result)
print("Bränsle efteråt:", car.fuel, "/", car.max_fuel)
print()

print("=== Test 8: Stoppa två gånger ===")
print("Anrop: car.stop()")
result = car.stop()
print("Returnerar:", result)
print("Anrop: car.stop()")
result = car.stop()
print("Returnerar:", result)
print("Motor igång efteråt:", car.is_running)
